src/main/java/org/unibl/etf/ip/bean/InfoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unibl.etf.ip.bean;

import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.ApplicationScoped;
import org.unibl.etf.ip.facade.StudentFacade;
import org.unibl.etf.ip.util.SessionCounter;

/**
 *
 * @author Željko Lojić <zeljko.lojic@yandex.com>
 */
@Named(value = "infoBean")
@ApplicationScoped
public class InfoBean {

    @EJB
    private StudentFacade studentFacade;

    public int getActiveUsers() {
        return SessionCounter.getCount();
    }

    public int getRegisteredUsers() {
        return studentFacade.count();
    }

}

src/main/webapp/WEB-INF/components/admin-header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:composition>
        <h:form>
            <p:outputLabel value="Number of active users: "/>
            <p:outputLabel value="#{infoBean.activeUsers}"/>
            <p:outputLabel value=" | "/>
            <p:outputLabel value="Number of registered users: "/>
            <p:outputLabel value="#{infoBean.registeredUsers}"/>
            <p:outputLabel value=" | "/>
            <p:link href="index.xhtml" value="Review"/>
            <p:outputLabel value=" | "/>
            <p:link href="users.xhtml" value="Users"/>
            <p:outputLabel value=" | "/>
            <p:link href="posts.xhtml" value="Posts"/>
            <p:outputLabel value=" | "/>
            <p:commandLink action="#{adminBean.logOut}" value="Log out"/>
            <p:separator/>
        </h:form>
    </ui:composition>
</html>

src/main/webapp/WEB-INF/components/ne-header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <p:link href="news.xhtml" value="Add news"/>
        <p:outputLabel value=" | "/>
        <p:link href="events.xhtml" value="Add event"/>
        <p:separator/>
    </ui:composition>
</html>